project:
  type: book
  resources:
    - src/
  output-dir: docs

book:
  title: "COMP/STAT 112: Introduction to Data Science"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
  downloads: [pdf]
  chapters:
    - index.qmd
    - src/01-RStudio_Intro.qmd

format:
  html:
    code-copy: true
    theme: cosmo
    css: styles/styles.css
    toc: true

execute:
  cache: true
  freeze: auto

